# NOTEBOOK DATA EXPLORATION :

###  Ce notebook contient tous les traitements qui ont été effectué sur notre dataset depuis le telechargement de données jusqu'a l'enregistrement des nouevelle données en passant par l'analyse et jusqu'au nettoyage de donnée.

## GROUPE MIA24 (Best Groupe)!

## Traitement Pandas

### chargement de données

In [1]:
import pandas as pd 

df_athletes = pd.read_json("Data_Brut/olympic_athletes.json")
df_result= pd.read_html('Data_Brut/olympic_results.html')[0]
df_medal = pd.read_excel('Data_Brut/olympic_medals.xlsx')
df_host=pd.read_xml('Data_Brut/olympic_hosts.xml')

## Traitement sur le dataframe athletes

In [2]:
df_athletes.head()

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth,athlete_medals,bio
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0,None,None
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0,None,None
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0,None,None
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0,None,None
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0,None,None

In [3]:
print("Nombre de ligne du dataframe:", len(df_athletes))
print(df_athletes.isnull().sum())

Nombre de ligne du dataframe: 75904
athlete_url                 0
athlete_full_name           0
games_participations        0
first_game                 22
athlete_year_birth       2456
athlete_medals          60552
bio                     53062
dtype: int64

### Sur le dataset athletes on a rencontré un problemes dans les valeur de la colonne athlete medals , on a constaté la présence de "/n" et donc on les a supprimé grace a un traitement pendas.

In [4]:
df_athletes["athlete_medals"].unique()

array([None, '\n\n\n1\n\nS\n\n', '\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nS\n\n', '\n\n\n1\n\nG\n\n',
       '\n\n\n1\n\nG\n\n\n\n1\n\nB\n\n', '\n\n\n2\n\nG\n\n\n\n1\n\nS\n\n',
       '\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n', '\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n2\n\nB\n\n', '\n\n\n1\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n1\n\nS\n\n', '\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n4\n\nS\n\n\n\n5\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n2\n\nS\n\n', '\n\n\n2\n\nG\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n', '\n\n\n2\n\nG\n\n',
       '\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n', '\n\n\n2\n\nG\n\n\n\n1\n\nB\n\n',
       '\n\n\n3\n\nB\n\n', '\n\n\n2\n\nS\n\n', '\n\n\n3\n\nG\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nB\n\n', '\n\n\n4\n\nG\n\n',
       '\n\n\n3\n\nG\n\n\n\n1\n\nB\n\n', '\n\n\n6\n\nG\n\n\n\n1\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n3\n\nS\n\n',
       '\n\n\n5\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n', '\n\n\n4\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n', '\n\n\n2\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n6\n\nS\n\n',
       '\n\n\n2\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n4\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n5\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nS\n\n', '\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n', '\n\n\n2\n\nG\n\n\n\n2\n\nS\n\n',
       '\n\n\n5\n\nG\n\n\n\n1\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n', '\n\n\n5\n\nG\n\n',
       '\n\n\n2\n\nS\n\n\n\n4\n\nB\n\n', '\n\n\n7\n\nG\n\n\n\n2\n\nS\n\n',
       '\n\n\n4\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n3\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n1\n\nS\n\n', '\n\n\n7\n\nG\n\n\n\n5\n\nS\n\n',
       '\n\n\n3\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n3\n\nS\n\n',
       '\n\n\n1\n\nG\n\n\n\n1\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n1\n\nS\n\n',
       '\n\n\n1\n\nG\n\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n4\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n3\n\nS\n\n',
       '\n\n\n4\n\nG\n\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n2\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n', '\n\n\n7\n\nG\n\n',
       '\n\n\n1\n\nG\n\n\n\n5\n\nS\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n', '\n\n\n2\n\nG\n\n\n\n3\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n2\n\nS\n\n',
       '\n\n\n4\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n3\n\nS\n\n', '\n\n\n3\n\nS\n\n',
       '\n\n\n8\n\nG\n\n\n\n4\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n', '\n\n\n4\n\nS\n\n',
       '\n\n\n8\n\nG\n\n', '\n\n\n3\n\nG\n\n\n\n4\n\nS\n\n',
       '\n\n\n2\n\nG\n\n\n\n2\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n23\n\nG\n\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n1\n\nS\n\n',
       '\n\n\n8\n\nG\n\n\n\n4\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n5\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n1\n\nB\n\n', '\n\n\n1\n\nG\n\n\n\n4\n\nS\n\n',
       '\n\n\n6\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n1\n\nS\n\n',
       '\n\n\n1\n\nG\n\n\n\n2\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n2\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n5\n\nS\n\n',
       '\n\n\n3\n\nG\n\n\n\n4\n\nS\n\n\n\n5\n\nB\n\n', '\n\n\n5\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n4\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n4\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n4\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n4\n\nB\n\n', '\n\n\n4\n\nG\n\n\n\n5\n\nS\n\n',
       '\n\n\n5\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nS\n\n\n\n6\n\nB\n\n',
       '\n\n\n8\n\nG\n\n\n\n3\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nS\n\n\n\n6\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n3\n\nS\n\n\n\n5\n\nB\n\n',
       '\n\n\n3\n\nS\n\n\n\n6\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n', '\n\n\n6\n\nG\n\n',
       '\n\n\n3\n\nG\n\n\n\n4\n\nB\n\n', '\n\n\n8\n\nG\n\n\n\n4\n\nS\n\n',
       '\n\n\n6\n\nB\n\n', '\n\n\n6\n\nG\n\n\n\n4\n\nB\n\n',
       '\n\n\n9\n\nG\n\n\n\n1\n\nS\n\n', '\n\n\n4\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n5\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n4\n\nS\n\n',
       '\n\n\n8\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n5\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n6\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n5\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n4\n\nS\n\n', '\n\n\n4\n\nG\n\n\n\n3\n\nS\n\n',
       '\n\n\n5\n\nG\n\n\n\n1\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n6\n\nG\n\n\n\n2\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n6\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n9\n\nG\n\n\n\n1\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n4\n\nS\n\n', '\n\n\n5\n\nS\n\n',
       '\n\n\n7\n\nG\n\n\n\n1\n\nS\n\n', '\n\n\n1\n\nG\n\n\n\n5\n\nB\n\n',
       '\n\n\n9\n\nG\n\n\n\n5\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n2\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n5\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n4\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n1\n\nG\n\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n',
       '\n\n\n7\n\nG\n\n\n\n1\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n3\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n2\n\nG\n\n\n\n5\n\nS\n\n',
       '\n\n\n2\n\nG\n\n\n\n1\n\nS\n\n\n\n6\n\nB\n\n',
       '\n\n\n3\n\nG\n\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n4\n\nG\n\n\n\n2\n\nS\n\n\n\n1\n\nB\n\n',
       '\n\n\n9\n\nG\n\n\n\n3\n\nS\n\n', '\n\n\n5\n\nG\n\n\n\n3\n\nS\n\n',
       '\n\n\n1\n\nS\n\n\n\n4\n\nB\n\n',
       '\n\n\n5\n\nG\n\n\n\n4\n\nS\n\n\n\n2\n\nB\n\n',
       '\n\n\n3\n\nS\n\n\n\n3\n\nB\n\n', '\n\n\n6\n\nG\n\n\n\n4\n\nS\n\n',
       '\n\n\n5\n\nS\n\n\n\n2\n\nB\n\n'], dtype=object)

In [5]:
import re
def clean_medal_info(value):
    if pd.isna(value):
        return value  
    cleaned_value = re.sub(r'[^123456789SBG]', '', value)
    return cleaned_value

df_athletes['athlete_medals'] = df_athletes['athlete_medals'].apply(clean_medal_info)

In [6]:
df_athletes.head(60)

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth,athlete_medals,bio
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0,None,None
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0,None,None
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0,None,None
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0,None,None
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0,None,None
5,https://olympics.com/en/athletes/matt-graham,Matt GRAHAM,3,Sochi 2014,1994.0,1S,None
6,https://olympics.com/en/athletes/ikuma-horishima,Ikuma HORISHIMA,2,PyeongChang 2018,1997.0,1B,None
7,https://olympics.com/en/athletes/daichi-hara,Daichi HARA,2,PyeongChang 2018,1997.0,1B,None
8,https://olympics.com/en/athletes/laurent-dumais,Laurent DUMAIS,1,Beijing 2022,1996.0,None,None
9,https://olympics.com/en/athletes/james-matheson,James MATHESON,2,PyeongChang 2018,1995.0,None,None
10,https://olympics.com/en/athletes/pavel-kolmakov,Pavel KOLMAKOV,3,Sochi 2014,1996.0,None,None
11,https://olympics.com/en/athletes/kosuke-sugimoto,Kosuke SUGIMOTO,1,Beijing 2022,1994.0,None,None
12,https://olympics.com/en/athletes/brodie-summers,Brodie SUMMERS,3,Sochi 2014,1993.0,None,None
13,https://olympics.com/en/athletes/severi-vierela,Severi VIERELA,1,Beijing 2022,2001.0,None,None
14,https://olympics.com/en/athletes/marco-tade,Marco TADE,1,Beijing 2022,1995.0,None,None
15,https://olympics.com/en/athletes/william-feneley,William FENELEY,1,Beijing 2022,1999.0,None,None
16,https://olympics.com/en/athletes/mikael-kingsbury,Mikael KINGSBURY,3,Sochi 2014,1992.0,1G2S,\n\n\nIn the period between his elite debut in...
17,https://olympics.com/en/athletes/so-matsuda,So MATSUDA,1,Beijing 2022,1999.0,None,None
18,https://olympics.com/en/athletes/wallberg,Walter WALLBERG,2,PyeongChang 2018,2000.0,1G,None
19,https://olympics.com/en/athletes/bradley-wilson,Bradley WILSON,3,Sochi 2014,1992.0,None,None
20,https://olympics.com/en/athletes/yang-zhao,Yang ZHAO,1,Beijing 2022,1992.0,None,None
21,https://olympics.com/en/athletes/benjamin-cavet,Benjamin CAVET,3,Sochi 2014,1994.0,None,None
22,https://olympics.com/en/athletes/cole-mcdonald,Cole MCDONALD,1,Beijing 2022,2003.0,None,None
23,https://olympics.com/en/athletes/nick-page,Nick PAGE,1,Beijing 2022,2002.0,None,None
24,https://olympics.com/en/athletes/sacha-theocharis,Sacha THEOCHARIS,2,PyeongChang 2018,1990.0,None,None
25,https://olympics.com/en/athletes/jimi-salonen,Jimi SALONEN,3,Sochi 2014,1994.0,None,None
26,https://olympics.com/en/athletes/nikita-novitskii,Nikita NOVITSKII,1,Beijing 2022,2000.0,None,None
27,https://olympics.com/en/athletes/nikita-andreev,Nikita ANDREEV,1,Beijing 2022,2004.0,None,None
28,https://olympics.com/en/athletes/ludvig-fjalls...,Ludvig FJALLSTROM,3,Sochi 2014,1993.0,None,None
29,https://olympics.com/en/athletes/oskar-elofsson,Oskar ELOFSSON,1,Beijing 2022,1998.0,None,None
30,https://olympics.com/en/athletes/bingqiang-mao,Bingqiang MAO,2,PyeongChang 2018,2001.0,None,None
31,https://olympics.com/en/athletes/kevin-rolland,Kevin ROLLAND,3,Sochi 2014,1989.0,1B,None
32,https://olympics.com/en/athletes/noah-bowman,Noah BOWMAN,3,Sochi 2014,1992.0,None,None
33,https://olympics.com/en/athletes/robin-briguet,Robin BRIGUET,2,PyeongChang 2018,1999.0,None,None
34,https://olympics.com/en/athletes/nico-porteous,Nico PORTEOUS,2,PyeongChang 2018,2001.0,1G1B,None
35,https://olympics.com/en/athletes/seung-hun-lee,Seung Hun LEE,1,Beijing 2022,2005.0,None,None
36,https://olympics.com/en/athletes/david-wise,David WISE,3,Sochi 2014,1990.0,2G1S,\n\n\nThe favourite heading into the inaugural...
37,https://olympics.com/en/athletes/aaron-blunck,Aaron BLUNCK,3,Sochi 2014,1996.0,None,None
38,https://olympics.com/en/athletes/brendan-mackay,Brendan MACKAY,1,Beijing 2022,1997.0,None,None
39,https://olympics.com/en/athletes/ben-harrington,Ben HARRINGTON,1,Beijing 2022,2001.0,None,None
40,https://olympics.com/en/athletes/sun-jingbo,Jingbo SUN,1,Beijing 2022,2003.0,None,None
41,https://olympics.com/en/athletes/alex-ferreira,Alex FERREIRA,2,PyeongChang 2018,1994.0,1S1B,None
42,https://olympics.com/en/athletes/miguel-porteous,Miguel PORTEOUS,2,PyeongChang 2018,1999.0,None,None
43,https://olympics.com/en/athletes/brendan-newby,Brendan NEWBY,2,PyeongChang 2018,1996.0,None,None
44,https://olympics.com/en/athletes/gus-kenworthy,Gus KENWORTHY,3,Sochi 2014,1991.0,1S,\n\n\nAFP World Championships overall titles i...
45,https://olympics.com/en/athletes/gustav-legnavsky,Gustav LEGNAVSKY,1,Beijing 2022,2005.0,None,None
46,https://olympics.com/en/athletes/haizhuo-wang,Haizhuo WANG,1,Beijing 2022,2003.0,None,None
47,https://olympics.com/en/athletes/marco-ladner,Marco LADNER,3,Sochi 2014,1998.0,None,None
48,https://olympics.com/en/athletes/binghan-he,Binghan HE,1,Beijing 2022,2003.0,None,None
49,https://olympics.com/en/athletes/birk-irving,Birk IRVING,1,Beijing 2022,1999.0,None,None
50,https://olympics.com/en/athletes/simon-d-artois,Simon D ARTOIS,1,Beijing 2022,1992.0,None,None
51,https://olympics.com/en/athletes/rafael-kreien...,Rafael KREIENBUEHL,2,PyeongChang 2018,1999.0,None,None
52,https://olympics.com/en/athletes/jon-sallinen,Jon SALLINEN,1,Beijing 2022,2000.0,None,None
53,https://olympics.com/en/athletes/edouard-therr...,Edouard THERRIAULT,1,Beijing 2022,2003.0,None,None
54,https://olympics.com/en/athletes/matej-svancer,Matej SVANCER,1,Beijing 2022,2004.0,None,None
55,https://olympics.com/en/athletes/teal-harle,Teal HARLE,2,PyeongChang 2018,1996.0,None,None
56,https://olympics.com/en/athletes/colin-wili,Colin WILI,1,Beijing 2022,1998.0,None,None
57,https://olympics.com/en/athletes/hugo-burvall,Hugo BURVALL,1,Beijing 2022,1997.0,None,None
58,https://olympics.com/en/athletes/leonardo-dona...,Leonardo DONAGGIO,1,Beijing 2022,2003.0,None,None
59,https://olympics.com/en/athletes/birk-ruud,Birk RUUD,1,Beijing 2022,2000.0,1G,None

### Pour optimisé le dataset on a décidé de rajouter 3 colonnes avec les différents types de médailles ainsi qu'une 4 eme pour le nombre total de médailes obtenu par chaque athletes.

In [7]:
def extract_medals(value):
    if pd.isna(value):
        return {'M_gold': 0, 'M_silver': 0, 'M_bronze': 0}
    
    gold = re.search(r'(\d+)G', value)
    silver = re.search(r'(\d+)S', value)
    bronze = re.search(r'(\d+)B', value)
    
    return {
        'M_gold': int(gold.group(1)) if gold else 0,
        'M_silver': int(silver.group(1)) if silver else 0,
        'M_bronze': int(bronze.group(1)) if bronze else 0
    }

medal_counts = df_athletes['athlete_medals'].apply(extract_medals)

medal_counts_df = pd.DataFrame(medal_counts.tolist())
df_athletes = pd.concat([df_athletes, medal_counts_df], axis=1)

In [8]:
df_athletes.head()

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth,athlete_medals,bio,M_gold,M_silver,M_bronze
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0,None,None,0,0,0
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0,None,None,0,0,0
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0,None,None,0,0,0
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0,None,None,0,0,0
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0,None,None,0,0,0

### Suppression de la colonne bio du df_ahletes

In [9]:
df_athletes = df_athletes.drop("bio",axis=1)
print(df_athletes.isnull().sum())

athlete_url                 0
athlete_full_name           0
games_participations        0
first_game                 22
athlete_year_birth       2456
athlete_medals          60552
M_gold                      0
M_silver                    0
M_bronze                    0
dtype: int64

### Suppression de la colonne bio du "athlete_medals"

In [10]:
df_athletes = df_athletes.drop("athlete_medals",axis=1)

In [11]:
df_athletes.head()

,athlete_url,athlete_full_name,games_participations,first_game,athlete_year_birth,M_gold,M_silver,M_bronze
0,https://olympics.com/en/athletes/cooper-woods-...,Cooper WOODS-TOPALOVIC,1,Beijing 2022,2000.0,0,0,0
1,https://olympics.com/en/athletes/elofsson,Felix ELOFSSON,2,PyeongChang 2018,1995.0,0,0,0
2,https://olympics.com/en/athletes/dylan-walczyk,Dylan WALCZYK,1,Beijing 2022,1993.0,0,0,0
3,https://olympics.com/en/athletes/olli-penttala,Olli PENTTALA,1,Beijing 2022,1995.0,0,0,0
4,https://olympics.com/en/athletes/reikherd,Dmitriy REIKHERD,1,Beijing 2022,1989.0,0,0,0

In [12]:
df_athletes['total_medals'] = df_athletes['M_gold'] + df_athletes['M_silver'] + df_athletes['M_bronze']

### Dataframe result

In [13]:
df_result.head()

,Unnamed: 0,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type
0,0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.co...",False,1,Italy,IT,ITA,NaN,NaN,NaN,NaN
1,1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en...",False,2,Norway,NO,NOR,NaN,NaN,NaN,NaN
2,2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/at...",False,3,Sweden,SE,SWE,NaN,NaN,NaN,NaN
3,3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/a...",False,4,Great Britain,GB,GBR,NaN,NaN,NaN,NaN
4,4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/ath...",False,5,Canada,CA,CAN,NaN,NaN,NaN,NaN

In [14]:
df_result=df_result.drop(columns=['Unnamed: 0'])

In [15]:
df_result.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,athletes,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_url,athlete_full_name,value_unit,value_type
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,"[('Stefania CONSTANTINI', 'https://olympics.co...",False,1,Italy,IT,ITA,NaN,NaN,NaN,NaN
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,"[('Kristin SKASLIEN', 'https://olympics.com/en...",False,2,Norway,NO,NOR,NaN,NaN,NaN,NaN
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,"[('Almida DE VAL', 'https://olympics.com/en/at...",False,3,Sweden,SE,SWE,NaN,NaN,NaN,NaN
3,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Jennifer DODDS', 'https://olympics.com/en/a...",False,4,Great Britain,GB,GBR,NaN,NaN,NaN,NaN
4,Curling,Mixed Doubles,beijing-2022,GameTeam,NaN,"[('Rachel HOMAN', 'https://olympics.com/en/ath...",False,5,Canada,CA,CAN,NaN,NaN,NaN,NaN

In [16]:
df_result=df_result.rename(columns={'slug_game': 'game_slug'})

In [17]:
df_result=df_result.drop(columns=["athletes"])
df_result=df_result.drop(columns=["athlete_url"])

### Dataframe medailles

In [18]:
df_medal.head()

,Unnamed: 0,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [19]:
df_medal=df_medal.drop(columns=['Unnamed: 0'])

In [20]:
df_medal.head()

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [21]:
df_medal=df_medal.rename(columns={'slug_game': 'game_slug'})

In [22]:
df_medal.head()

,discipline_title,game_slug,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/stefania-cons...,Stefania CONSTANTINI,Italy,IT,ITA
1,Curling,beijing-2022,Mixed Doubles,Mixed,GOLD,GameTeam,Italy,https://olympics.com/en/athletes/amos-mosaner,Amos MOSANER,Italy,IT,ITA
2,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/kristin-skaslien,Kristin SKASLIEN,Norway,NO,NOR
3,Curling,beijing-2022,Mixed Doubles,Mixed,SILVER,GameTeam,Norway,https://olympics.com/en/athletes/magnus-nedreg...,Magnus NEDREGOTTEN,Norway,NO,NOR
4,Curling,beijing-2022,Mixed Doubles,Mixed,BRONZE,GameTeam,Sweden,https://olympics.com/en/athletes/almida-de-val,Almida DE VAL,Sweden,SE,SWE

In [23]:
print("Nombre de ligne du dataframe:", len(df_medal))
print(df_medal.isnull().sum())

Nombre de ligne du dataframe: 21697
discipline_title             0
game_slug                    0
event_title                  0
event_gender                 0
medal_type                   0
participant_type             0
participant_title        15113
athlete_url               4670
athlete_full_name         3624
country_name                 0
country_code              1502
country_3_letter_code        0
dtype: int64

### Dataframe host

In [24]:
df_host.head()

,index,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014

In [25]:
df_host=df_host.drop(columns=["index"])

In [26]:
df_host.head(10)

,game_slug,game_end_date,game_start_date,game_location,game_name,game_season,game_year
0,beijing-2022,2022-02-20T12:00:00Z,2022-02-04T15:00:00Z,China,Beijing 2022,Winter,2022
1,tokyo-2020,2021-08-08T14:00:00Z,2021-07-23T11:00:00Z,Japan,Tokyo 2020,Summer,2020
2,pyeongchang-2018,2018-02-25T08:00:00Z,2018-02-08T23:00:00Z,Republic of Korea,PyeongChang 2018,Winter,2018
3,rio-2016,2016-08-21T21:00:00Z,2016-08-05T12:00:00Z,Brazil,Rio 2016,Summer,2016
4,sochi-2014,2014-02-23T16:00:00Z,2014-02-07T04:00:00Z,Russian Federation,Sochi 2014,Winter,2014
5,london-2012,2012-08-12T19:00:00Z,2012-07-27T07:00:00Z,Great Britain,London 2012,Summer,2012
6,vancouver-2010,2010-02-28T04:00:00Z,2010-02-12T16:00:00Z,Canada,Vancouver 2010,Winter,2010
7,beijing-2008,2008-08-24T12:00:00Z,2008-08-08T00:00:00Z,China,Beijing 2008,Summer,2008
8,turin-2006,2006-02-26T19:00:00Z,2006-02-10T07:00:00Z,Italy,Turin 2006,Winter,2006
9,athens-2004,2004-08-29T18:00:00Z,2004-08-13T06:00:00Z,Greece,Athens 2004,Summer,2004

In [27]:
print("Nombre de ligne du dataframe:", len(df_host))
print(df_host.isnull().sum())

Nombre de ligne du dataframe: 53
game_slug          0
game_end_date      0
game_start_date    0
game_location      0
game_name          0
game_season        0
game_year          0
dtype: int64

### Enregistrement de la premiere version de donnée en CSV

In [28]:
df_athletes.to_csv("Data/athletes.csv",index=False)
df_host.to_csv('Data/host.csv',index=False)
df_medal.to_csv('Data/medal.csv',index=False)
df_result.to_csv('Data/result.csv',index=False)

## Traitement PYSPARK

#### Ouverture d'une session spark

In [29]:

from pyspark.sql import SparkSession

# Créer une session Spark
spark = SparkSession.builder \
    .appName("Hackathon") \
    .getOrCreate()

24/05/29 14:19:31 WARN Utils: Your hostname, novagen-XPS-13-9300 resolves to a loopback address: 127.0.1.1; using 192.168.0.32 instead (on interface wlp0s20f3)
24/05/29 14:19:31 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/05/29 14:19:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [30]:
from pyspark.sql.functions import col, sum,countDistinct, when,count,collect_list

#### Chargement des données au format spark.

In [31]:
data_athletes = spark.read.csv("Data/athletes.csv", header=True, inferSchema=True)
data_host= spark.read.csv("Data/host.csv", header=True, inferSchema=True)
data_medal = spark.read.csv("Data/medal.csv", header=True, inferSchema=True)
data_result=spark.read.csv("Data/result.csv", header=True, inferSchema=True)

### Analyse et traitement du dataset data athlete :

In [32]:
data_athletes.show()

+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
|         athlete_url|   athlete_full_name|games_participations|      first_game|athlete_year_birth|M_gold|M_silver|M_bronze|total_medals|
+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
|https://olympics....|Cooper WOODS-TOPA...|                   1|    Beijing 2022|            2000.0|     0|       0|       0|           0|
|https://olympics....|      Felix ELOFSSON|                   2|PyeongChang 2018|            1995.0|     0|       0|       0|           0|
|https://olympics....|       Dylan WALCZYK|                   1|    Beijing 2022|            1993.0|     0|       0|       0|           0|
|https://olympics....|       Olli PENTTALA|                   1|    Beijing 2022|            1995.0|     0|       0|       0|           0|
|https://olympics....|    Dmitriy REIKHERD|                   1|    Beijing 2022|            1989.0|     0|       0|       0|           0|
|https://olympics....|         Matt GRAHAM|                   3|      Sochi 2014|            1994.0|     0|       1|       0|           1|
|https://olympics....|     Ikuma HORISHIMA|                   2|PyeongChang 2018|            1997.0|     0|       0|       1|           1|
|https://olympics....|         Daichi HARA|                   2|PyeongChang 2018|            1997.0|     0|       0|       1|           1|
|https://olympics....|      Laurent DUMAIS|                   1|    Beijing 2022|            1996.0|     0|       0|       0|           0|
|https://olympics....|      James MATHESON|                   2|PyeongChang 2018|            1995.0|     0|       0|       0|           0|
|https://olympics....|      Pavel KOLMAKOV|                   3|      Sochi 2014|            1996.0|     0|       0|       0|           0|
|https://olympics....|     Kosuke SUGIMOTO|                   1|    Beijing 2022|            1994.0|     0|       0|       0|           0|
|https://olympics....|      Brodie SUMMERS|                   3|      Sochi 2014|            1993.0|     0|       0|       0|           0|
|https://olympics....|      Severi VIERELA|                   1|    Beijing 2022|            2001.0|     0|       0|       0|           0|
|https://olympics....|          Marco TADE|                   1|    Beijing 2022|            1995.0|     0|       0|       0|           0|
|https://olympics....|     William FENELEY|                   1|    Beijing 2022|            1999.0|     0|       0|       0|           0|
|https://olympics....|    Mikael KINGSBURY|                   3|      Sochi 2014|            1992.0|     1|       2|       0|           3|
|https://olympics....|          So MATSUDA|                   1|    Beijing 2022|            1999.0|     0|       0|       0|           0|
|https://olympics....|     Walter WALLBERG|                   2|PyeongChang 2018|            2000.0|     1|       0|       0|           1|
|https://olympics....|      Bradley WILSON|                   3|      Sochi 2014|            1992.0|     0|       0|       0|           0|
+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
only showing top 20 rows

In [33]:
data_athletes.printSchema()

root
 |-- athlete_url: string (nullable = true)
 |-- athlete_full_name: string (nullable = true)
 |-- games_participations: integer (nullable = true)
 |-- first_game: string (nullable = true)
 |-- athlete_year_birth: double (nullable = true)
 |-- M_gold: integer (nullable = true)
 |-- M_silver: integer (nullable = true)
 |-- M_bronze: integer (nullable = true)
 |-- total_medals: integer (nullable = true)

In [34]:
data_athletes.count()

75904

In [35]:
data_athletes=data_athletes.filter(
   ~(data_athletes.athlete_full_name.isNull() & 
      data_athletes.games_participations.isNull() & 
      data_athletes.first_game.isNull() & 
      data_athletes.athlete_year_birth.isNull())
)

In [36]:
data_athletes = data_athletes.dropna(subset=["first_game"])
data_athletes = data_athletes.dropna(subset=["athlete_year_birth"])

In [37]:
data_athletes.show()

+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
|         athlete_url|   athlete_full_name|games_participations|      first_game|athlete_year_birth|M_gold|M_silver|M_bronze|total_medals|
+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
|https://olympics....|Cooper WOODS-TOPA...|                   1|    Beijing 2022|            2000.0|     0|       0|       0|           0|
|https://olympics....|      Felix ELOFSSON|                   2|PyeongChang 2018|            1995.0|     0|       0|       0|           0|
|https://olympics....|       Dylan WALCZYK|                   1|    Beijing 2022|            1993.0|     0|       0|       0|           0|
|https://olympics....|       Olli PENTTALA|                   1|    Beijing 2022|            1995.0|     0|       0|       0|           0|
|https://olympics....|    Dmitriy REIKHERD|                   1|    Beijing 2022|            1989.0|     0|       0|       0|           0|
|https://olympics....|         Matt GRAHAM|                   3|      Sochi 2014|            1994.0|     0|       1|       0|           1|
|https://olympics....|     Ikuma HORISHIMA|                   2|PyeongChang 2018|            1997.0|     0|       0|       1|           1|
|https://olympics....|         Daichi HARA|                   2|PyeongChang 2018|            1997.0|     0|       0|       1|           1|
|https://olympics....|      Laurent DUMAIS|                   1|    Beijing 2022|            1996.0|     0|       0|       0|           0|
|https://olympics....|      James MATHESON|                   2|PyeongChang 2018|            1995.0|     0|       0|       0|           0|
|https://olympics....|      Pavel KOLMAKOV|                   3|      Sochi 2014|            1996.0|     0|       0|       0|           0|
|https://olympics....|     Kosuke SUGIMOTO|                   1|    Beijing 2022|            1994.0|     0|       0|       0|           0|
|https://olympics....|      Brodie SUMMERS|                   3|      Sochi 2014|            1993.0|     0|       0|       0|           0|
|https://olympics....|      Severi VIERELA|                   1|    Beijing 2022|            2001.0|     0|       0|       0|           0|
|https://olympics....|          Marco TADE|                   1|    Beijing 2022|            1995.0|     0|       0|       0|           0|
|https://olympics....|     William FENELEY|                   1|    Beijing 2022|            1999.0|     0|       0|       0|           0|
|https://olympics....|    Mikael KINGSBURY|                   3|      Sochi 2014|            1992.0|     1|       2|       0|           3|
|https://olympics....|          So MATSUDA|                   1|    Beijing 2022|            1999.0|     0|       0|       0|           0|
|https://olympics....|     Walter WALLBERG|                   2|PyeongChang 2018|            2000.0|     1|       0|       0|           1|
|https://olympics....|      Bradley WILSON|                   3|      Sochi 2014|            1992.0|     0|       0|       0|           0|
+--------------------+--------------------+--------------------+----------------+------------------+------+--------+--------+------------+
only showing top 20 rows

### Analyse et traitement du dataset data_result:

In [38]:
data_result.show()

+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
|discipline_title|  event_title|   game_slug|participant_type|medal_type|rank_equal|rank_position|        country_name|country_code|country_3_letter_code|athlete_full_name|value_unit|value_type|
+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      GOLD|     false|            1|               Italy|          IT|                  ITA|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    SILVER|     false|            2|              Norway|          NO|                  NOR|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    BRONZE|     false|            3|              Sweden|          SE|                  SWE|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            4|       Great Britain|          GB|                  GBR|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            5|              Canada|          CA|                  CAN|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            6|      Czech Republic|          CZ|                  CZE|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            7|         Switzerland|          CH|                  SUI|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            8|United States of ...|          US|                  USA|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            9|People's Republic...|          CN|                  CHN|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|           10|           Australia|          AU|                  AUS|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      GOLD|     false|            1|       Great Britain|          GB|                  GBR|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|    SILVER|     false|            2|               Japan|          JP|                  JPN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|    BRONZE|     false|            3|              Sweden|          SE|                  SWE|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            4|         Switzerland|          CH|                  SUI|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            5|              Canada|          CA|                  CAN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            6|United States of ...|          US|                  USA|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            7|People's Republic...|          CN|                  CHN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            8|   Republic of Korea|          KR|                  KOR|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            9|             Denmark|          DK|                  DEN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|           10|                 ROC|         ROC|                  ROC|             NULL|      NULL|      NULL|
+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
only showing top 20 rows

In [39]:
data_result.printSchema()

root
 |-- discipline_title: string (nullable = true)
 |-- event_title: string (nullable = true)
 |-- game_slug: string (nullable = true)
 |-- participant_type: string (nullable = true)
 |-- medal_type: string (nullable = true)
 |-- rank_equal: boolean (nullable = true)
 |-- rank_position: string (nullable = true)
 |-- country_name: string (nullable = true)
 |-- country_code: string (nullable = true)
 |-- country_3_letter_code: string (nullable = true)
 |-- athlete_full_name: string (nullable = true)
 |-- value_unit: string (nullable = true)
 |-- value_type: string (nullable = true)

In [40]:
data_result.distinct().show()

+--------------------+--------------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+--------------------+----------+----------+
|    discipline_title|         event_title|   game_slug|participant_type|medal_type|rank_equal|rank_position|        country_name|country_code|country_3_letter_code|   athlete_full_name|value_unit|value_type|
+--------------------+--------------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+--------------------+----------+----------+
|           Snowboard|Men's Snowboard S...|beijing-2022|         Athlete|      GOLD|     false|            1|              Canada|          CA|                  CAN|          Max PARROT|     70.11|    POINTS|
|       Speed skating|       Women's 5000m|beijing-2022|         Athlete|    BRONZE|     false|            3|      Czech Republic|          CZ|                  CZE|   Martina SABLIKOVA|   6:50.09|      TIME|
|            Biathlon|Women's 12.5km Ma...|beijing-2022|         Athlete|    BRONZE|     false|            3|              Norway|          NO|                  NOR|Marte Olsbu ROEIS...|   40:52.9|      TIME|
|Cross Country Skiing|Men's 15km + 15km...|beijing-2022|         Athlete|      GOLD|     false|            1|                 ROC|         ROC|                  ROC| Alexander BOLSHUNOV| 1:16:09.8|      TIME|
| Artistic Gymnastics|Women's Floor Exe...|  tokyo-2020|         Athlete|    SILVER|     false|            2|               Italy|          IT|                  ITA|     Vanessa FERRARI|    14.166|    POINTS|
|       Weightlifting|        Men's +109kg|  tokyo-2020|         Athlete|    SILVER|     false|            2|Islamic Republic ...|          IR|                  IRI|         Ali DAVOUDI|       441|    WEIGHT|
|           Athletics|Women's 400m Hurdles|  tokyo-2020|         Athlete|    BRONZE|     false|            3|         Netherlands|          NL|                  NED|           Femke BOL|     54043|      TIME|
|           Athletics|      Men's Shot Put|  tokyo-2020|         Athlete|    SILVER|     false|            2|United States of ...|          US|                  USA|          Joe KOVACS|     20.93|  DISTANCE|
|           Athletics| Men's Javelin Throw|  tokyo-2020|         Athlete|      GOLD|     false|            1|               India|          IN|                  IND|       Neeraj CHOPRA|     86.65|  DISTANCE|
|            Biathlon|Women's 15km Indi...|beijing-2022|         Athlete|    SILVER|     false|            2|              France|          FR|                  FRA|     Anais CHEVALIER|   44:22.1|      TIME|
|       Alpine Skiing|  Men's Giant Slalom|beijing-2022|         Athlete|    BRONZE|     false|            3|              France|          FR|                  FRA|      Mathieu FAIVRE|   2:10.69|      TIME|
|      Sport Climbing|      Men's Combined|  tokyo-2020|         Athlete|    SILVER|     false|            2|United States of ...|          US|                  USA|   Nathaniel COLEMAN|        30|    POINTS|
|           Athletics|   Women's Long Jump|  tokyo-2020|         Athlete|      GOLD|     false|            1|             Germany|          DE|                  GER|     Malaika MIHAMBO|      6.98|  DISTANCE|
|            Swimming|Men's 100m Backst...|  tokyo-2020|         Athlete|      GOLD|     false|            1|                 ROC|         ROC|                  ROC|        Evgeny RYLOV|     53022|      TIME|
|           Snowboard|Women's Snowboard...|beijing-2022|         Athlete|      GOLD|     false|            1|United States of ...|          US|                  USA|           Chloe KIM|     87.75|    POINTS|
|Cross Country Skiing|Women's 10km Classic|beijing-2022|         Athlete|    BRONZE|     false|            3|             Finland|          FI|                  FIN|   Krista PARMAKOSKI|   28:37.8|      TIME|
|           Snowboard|Men's Snowboard B...|beijing-2022|         Athlete|    SILVER|     false|            2|              Norway|          NO|                  NOR|       Mons ROISLAND|    146.50|    POINTS|
|Cross Country Skiing|Men's 15km + 15km...|beijing-2022|         Athlete|    SILVER|     false|            2|                 ROC|         ROC|                  ROC|       Denis SPITSOV| 1:17:20.8|      TIME|
| Artistic Gymnastics|         Men's Rings|  tokyo-2020|         Athlete|      GOLD|     false|            1|People's Republic...|          CN|                  CHN|            Yang LIU|    15.300|    POINTS|
|           Athletics|        Women's 200m|  tokyo-2020|         Athlete|      GOLD|     false|            1|             Jamaica|          JM|                  JAM|     Elaine THOMPSON|     22086|      TIME|
+--------------------+--------------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+--------------------+----------+----------+
only showing top 20 rows

In [41]:
data_result.count()

162804

In [42]:
data_result.groupBy("discipline_title").count().show()

+--------------------+-----+
|    discipline_title|count|
+--------------------+-----+
|              Tennis| 2297|
|              Boxing| 6816|
|          Ice Hockey|  349|
|   Marathon Swimming|  202|
|                Golf|  385|
|              Rowing| 2812|
|                Judo| 3803|
|   Baseball/Softball|   12|
|            Softball|   32|
|             Sailing| 3886|
|            Swimming|14704|
|         Cycling BMX|  108|
|Cycling BMX Frees...|   18|
|       Alpine Skiing|10185|
|          Basketball|  408|
|            Handball|  276|
| Rhythmic Gymnastics|   18|
|            Biathlon| 5057|
|              Karate|   81|
|           Triathlon|  652|
+--------------------+-----+
only showing top 20 rows

In [43]:
data_result.groupBy("participant_type").count().show()

+----------------+------+
|participant_type| count|
+----------------+------+
|         Athlete|141646|
|        GameTeam| 21158|
+----------------+------+

In [44]:
data_result.groupBy("medal_type").count().show()

+----------+------+
|medal_type| count|
+----------+------+
|      NULL|142598|
|    SILVER|  6568|
|      GOLD|  6609|
|    BRONZE|  7029|
+----------+------+

In [45]:
data_result.groupBy("participant_type").count().show()

+----------------+------+
|participant_type| count|
+----------------+------+
|         Athlete|141646|
|        GameTeam| 21158|
+----------------+------+

In [46]:
data_result.groupBy("game_slug").count().show()
data_result.groupBy("game_slug").count().count()

+-------------------+-----+
|          game_slug|count|
+-------------------+-----+
|         sochi-2014| 3666|
|       beijing-2022| 3784|
|        london-2012| 7531|
|     vancouver-2010| 3322|
|       beijing-2008| 7360|
|         tokyo-2020| 6863|
|           rio-2016| 7672|
|   pyeongchang-2018| 3707|
|        nagano-1998| 2659|
|        athens-2004| 6979|
|salt-lake-city-2002| 3008|
|         turin-2006| 3256|
|       atlanta-1996| 7117|
|   albertville-1992| 2783|
|     barcelona-1992| 6878|
|   lillehammer-1994| 2451|
|        sydney-2000| 7091|
|      sarajevo-1984| 1664|
|   mexico-city-1968| 3569|
|      montreal-1976| 3670|
+-------------------+-----+
only showing top 20 rows

53

In [47]:
data_result.groupBy("event_title").count().show()

+--------------------+-----+
|         event_title|count|
+--------------------+-----+
|Men's Snowboard S...|   30|
|     Women's Monobob|   20|
|Men's Light Heavy...|   22|
|    110m hurdles men|  313|
|sabre individual men|  583|
|          Keirin men|   88|
|   4x7.5km relay men|   19|
|K2 1000m kayak do...|  169|
|60 66kg halflight...|  129|
|Beijing 2008 Taek...|   16|
|     Women's Madison|   15|
|          Men's 96kg|   13|
|       Dressage Team|   15|
|Women's 4 x 100m ...|    8|
|Ladiesâ 3000m R...|    8|
|Ladiesâ Alpine ...|   32|
|Men's Parallel Gi...|   32|
|        Women's 200m|    8|
|  10m platform women|  416|
|100m backstroke w...|  489|
+--------------------+-----+
only showing top 20 rows

In [49]:
data_result.groupBy("rank_equal").count().show()

+----------+------+
|rank_equal| count|
+----------+------+
|      NULL|130278|
|      true| 23613|
|     false|  8913|
+----------+------+

In [50]:
#Verification si un pays a plusieur codes
data_result_grouped = data_result.groupBy('country_name').agg(countDistinct('country_3_letter_code').alias('distinct_code_count'))

data_result_filtered = data_result_grouped.filter(col('distinct_code_count') > 1)

data_result_filtered_pandas = data_result_filtered.toPandas()

data_result_filtered_pandas

Empty DataFrame
Columns: [country_name, distinct_code_count]
Index: []

In [51]:
#Verification si un code a plusieur pays
data_result_grouped = data_result.groupBy('country_3_letter_code').agg(countDistinct('country_name').alias('DistinctCountryCount'))

data_result_filtered = data_result_grouped.filter(data_result_grouped['DistinctCountryCount'] > 1)
data_result_filtered_pandas = data_result_filtered.toPandas()
data_result_filtered_pandas

  country_3_letter_code  DistinctCountryCount
0                   IVB                     2
1                   CIV                     2
2                   ISV                     2
3                   SWZ                     2
4                   MKD                     2

In [52]:
#Affichage des pays avec le meme code
data_result_grouped = data_result.groupBy('country_3_letter_code').agg(countDistinct('country_name').alias('DistinctCountryCount'))

data_result_filtered = data_result_grouped.filter(data_result_grouped['DistinctCountryCount'] > 1)

codes_with_multiple_countries = [row['country_3_letter_code'] for row in data_result_filtered.collect()]

df_filtered_rows = data_result.filter(col('country_3_letter_code').isin(codes_with_multiple_countries))

df_distinct_pairs = df_filtered_rows.select('country_name', 'country_3_letter_code').distinct()

data_result_filtered_pandas = df_distinct_pairs.toPandas()

data_result_filtered_pandas

                                country_name country_3_letter_code
0                          US Virgin Islands                   ISV
1                                  Swaziland                   SWZ
2                             CÃ´te d'Ivoire                   CIV
3                    Virgin Islands, British                   IVB
4  The Former Yugoslav Republic of Macedonia                   MKD
5                     British Virgin Islands                   IVB
6                                   Eswatini                   SWZ
7                            North Macedonia                   MKD
8                         Virgin Islands, US                   ISV
9                                Ivory Coast                   CIV

In [53]:
#Unification des nom de pays
from pyspark.sql.functions import when, col
data_result_updated = data_result.withColumn(
    'country_name',
     when(col('country_3_letter_code') == 'MKD', 'Republic of North Macedonia')
    .when(col('country_3_letter_code') == 'ISV', 'Virgin Islands, US')
    .when(col('country_3_letter_code') == 'IVB', 'Virgin Islands, British')
    .when(col('country_3_letter_code') == 'CIV', 'Ivory Coast')
    .when(col('country_3_letter_code') == 'SWZ', 'Eswatini')
    .otherwise(col('country_name'))
)
data_result_filtered_pandas = data_result_updated.toPandas()
data_result_filtered_pandas

,discipline_title,event_title,game_slug,participant_type,medal_type,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_full_name,value_unit,value_type
0,Curling,Mixed Doubles,beijing-2022,GameTeam,GOLD,False,1,Italy,IT,ITA,None,None,None
1,Curling,Mixed Doubles,beijing-2022,GameTeam,SILVER,False,2,Norway,NO,NOR,None,None,None
2,Curling,Mixed Doubles,beijing-2022,GameTeam,BRONZE,False,3,Sweden,SE,SWE,None,None,None
3,Curling,Mixed Doubles,beijing-2022,GameTeam,None,False,4,Great Britain,GB,GBR,None,None,None
4,Curling,Mixed Doubles,beijing-2022,GameTeam,None,False,5,Canada,CA,CAN,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162799,Ski Jumping,Normal Hill Individual men,chamonix-1924,Athlete,None,None,DNS,Poland,PL,POL,Franciszek BUJAK,None,IRM
162800,Ski Jumping,Normal Hill Individual men,chamonix-1924,Athlete,None,None,DNS,Poland,PL,POL,Henryk MÃ¼ckenbrunn,None,IRM
162801,Ski Jumping,Normal Hill Individual men,chamonix-1924,Athlete,None,None,DNS,Czechoslovakia,CSHH,TCH,Milda Prokopec,None,IRM
162802,Ski Jumping,Normal Hill Individual men,chamonix-1924,Athlete,None,None,DNS,United States of America,US,USA,Sigurd Overby,None,IRM
162803,Gymnastics Artistic,"26th Federal Festival, Society and Association...",paris-1900,GameTeam,None,None,1,France,FR,FRA,None,142 pts,POINTS

In [54]:
#Verification de la correction
data_result_grouped = data_result_updated.groupBy('country_3_letter_code').agg(countDistinct('country_name').alias('DistinctCountryCount'))

data_result_filtered = data_result_grouped.filter(data_result_grouped['DistinctCountryCount'] > 1)

codes_with_multiple_countries = [row['country_3_letter_code'] for row in data_result_filtered.collect()]

df_filtered_rows = data_result.filter(col('country_3_letter_code').isin(codes_with_multiple_countries))

df_distinct_pairs = df_filtered_rows.select('country_name', 'country_3_letter_code').distinct()
data_result_filtered_pandas = df_distinct_pairs.toPandas()


data_result_filtered_pandas

Empty DataFrame
Columns: [country_name, country_3_letter_code]
Index: []

In [55]:
data_result = data_result_updated

In [56]:
#Verification des pays sans country_code (suspicion: pays sans country_code = pays non existant ou qui on changer de nom)
countries_without_code = data_result.filter((col("country_code").isNull()) | (col("country_code") == "") |
                                   (col("country_3_letter_code").isNull()) | (col("country_3_letter_code") == ""))

countries_without_code_show = countries_without_code.select("country_name", "country_code", "country_3_letter_code").dropDuplicates(["country_name"])
countries_show = countries_without_code_show.toPandas()
countries_show

                    country_name country_code country_3_letter_code
0                    Australasia         None                   ANZ
1                        Bohemia         None                   BOH
2                     Korea Team         None                   COR
3                        Lebanon         None                   LBN
4                            MIX         None                   MIX
5                         Malaya         None                   MAL
6                        Namibia         None                   NAM
7                   Newfoundland         None                   NFL
8                        Nigeria         None                   NGR
9                   North Borneo         None                   NBO
10                        Norway         None                   NOR
11  Olympic Athletes from Russia         None                   OAR
12      Refugee Olympic Athletes         None                   XXB
13          Refugee Olympic Team         None                   EOR
14                          Saar         None                   SAA
15                     Singapore         None                   SGP
16                 South Vietnam         None                   VNM
17                  Soviet Union         None                   URS
18                  Unified Team         None                   EUN
19          United Arab Republic         None                   UAR
20        West Indies Federation         None                   WIF
21                        Zambia         None                   ZAM

In [57]:
countries_without_code_number=countries_without_code.count()
print(f"Number of rows without a country code: {countries_without_code_number}")

Number of rows without a country code: 5036

In [58]:
#Unification des nom de la Russie
data_result_last = data_result.withColumn(
    "country_3_letter_code",
    when(
        col("country_name").contains("Olympic Athletes from Russia"), "RUS"
    ).when(
        col("country_name").contains("Soviet Union"), "RUS"
    ).otherwise(col("country_3_letter_code"))
).withColumn(
    "country_code",
    when(
        col("country_name").contains("Olympic Athletes from Russia"), "RU"
    ).when(
        col("country_name").contains("Soviet Union"), "RU"
    ).otherwise(col("country_code"))
)

data_result_last_show = data_result_last.filter(
    (col("country_name").contains("Olympic Athletes from Russia")) |
    (col("country_name").contains("Soviet Union"))
)
data_result_last_show = data_result_last_show.toPandas()
data_result_last_show

,discipline_title,event_title,game_slug,participant_type,medal_type,rank_equal,rank_position,country_name,country_code,country_3_letter_code,athlete_full_name,value_unit,value_type
0,Skeleton,Men,pyeongchang-2018,Athlete,SILVER,None,2,Olympic Athletes from Russia,RU,RUS,Nikita TREGUBOV,202180,TIME
1,Skeleton,Men,pyeongchang-2018,Athlete,None,None,15,Olympic Athletes from Russia,RU,RUS,Vladislav MARCHENKOV,205180,TIME
2,Speed skating,Ladiesâ 500m,pyeongchang-2018,Athlete,None,None,7,Olympic Athletes from Russia,RU,RUS,Angelina GOLIKOVA,37620,TIME
3,Speed skating,Menâs 1500m,pyeongchang-2018,Athlete,None,None,18,Olympic Athletes from Russia,RU,RUS,Sergey TROFIMOV,106690,TIME
4,Speed skating,Ladiesâ 3000m,pyeongchang-2018,Athlete,None,None,10,Olympic Athletes from Russia,RU,RUS,Natalia VORONINA,245850,TIME
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3265,Alpine Skiing,slalom men,lake-placid-1980,Athlete,None,None,DNF,Soviet Union,RU,RUS,Aleksandr ZHIROV,None,IRM
3266,Alpine Skiing,slalom men,lake-placid-1980,Athlete,None,None,DNS,Soviet Union,RU,RUS,Valery Tsyganov,None,IRM
3267,Figure skating,Ice dancing mixed,innsbruck-1976,GameTeam,GOLD,None,1,Soviet Union,RU,RUS,None,9Ã1+,RANK
3268,Figure skating,Ice dancing mixed,innsbruck-1976,GameTeam,SILVER,None,2,Soviet Union,RU,RUS,None,7Ã2+,RANK
3269,Figure skating,Ice dancing mixed,innsbruck-1976,GameTeam,None,None,4,Soviet Union,RU,RUS,None,8Ã4+,RANK

In [59]:
data_result_last_show.count()

discipline_title         3270
event_title              3270
game_slug                3270
participant_type         3270
medal_type               1221
rank_equal                300
rank_position            3248
country_name             3270
country_code             3270
country_3_letter_code    3270
athlete_full_name        2808
value_unit               2275
value_type               2391
dtype: int64

In [60]:
#Verification du nombre de pays sans country_code après la correction pour la Russie
countries_without_code = data_result_last.filter((col("country_code").isNull()) | (col("country_code") == "") |
                                   (col("country_3_letter_code").isNull()) | (col("country_3_letter_code") == ""))

countries_without_code_show = countries_without_code.select("country_name", "country_code", "country_3_letter_code").dropDuplicates(["country_name"])
countries_without_code_number=countries_without_code.count()
print(f"Number of rows without a country code: {countries_without_code_number}")

Number of rows without a country code: 1766

In [61]:
#Le nombre est negligable, on efface
data_result = data_result_last.filter((col("country_code").isNotNull()) & (col("country_code") != ""))

In [62]:
data_result.show()

+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
|discipline_title|  event_title|   game_slug|participant_type|medal_type|rank_equal|rank_position|        country_name|country_code|country_3_letter_code|athlete_full_name|value_unit|value_type|
+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      GOLD|     false|            1|               Italy|          IT|                  ITA|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    SILVER|     false|            2|              Norway|          NO|                  NOR|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    BRONZE|     false|            3|              Sweden|          SE|                  SWE|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            4|       Great Britain|          GB|                  GBR|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            5|              Canada|          CA|                  CAN|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            6|      Czech Republic|          CZ|                  CZE|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            7|         Switzerland|          CH|                  SUI|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            8|United States of ...|          US|                  USA|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|            9|People's Republic...|          CN|                  CHN|             NULL|      NULL|      NULL|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|     false|           10|           Australia|          AU|                  AUS|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      GOLD|     false|            1|       Great Britain|          GB|                  GBR|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|    SILVER|     false|            2|               Japan|          JP|                  JPN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|    BRONZE|     false|            3|              Sweden|          SE|                  SWE|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            4|         Switzerland|          CH|                  SUI|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            5|              Canada|          CA|                  CAN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            6|United States of ...|          US|                  USA|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            7|People's Republic...|          CN|                  CHN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            8|   Republic of Korea|          KR|                  KOR|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|            9|             Denmark|          DK|                  DEN|             NULL|      NULL|      NULL|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|     false|           10|                 ROC|         ROC|                  ROC|             NULL|      NULL|      NULL|
+----------------+-------------+------------+----------------+----------+----------+-------------+--------------------+------------+---------------------+-----------------+----------+----------+
only showing top 20 rows

In [63]:
data_result=data_result.drop("athlete_full_name")
data_result=data_result.drop("value_unit")
data_result=data_result.drop("value_type")
data_result=data_result.drop("country_code")
data_result=data_result.drop("rank_equal")
data_result=data_result.drop("rank_equal")

In [64]:
data_result.show()

+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
|discipline_title|  event_title|   game_slug|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|
+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      GOLD|            1|               Italy|                  ITA|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    SILVER|            2|              Norway|                  NOR|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            4|       Great Britain|                  GBR|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            5|              Canada|                  CAN|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            6|      Czech Republic|                  CZE|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            7|         Switzerland|                  SUI|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            8|United States of ...|                  USA|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|            9|People's Republic...|                  CHN|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      NULL|           10|           Australia|                  AUS|
|         Curling|        Women|beijing-2022|        GameTeam|      GOLD|            1|       Great Britain|                  GBR|
|         Curling|        Women|beijing-2022|        GameTeam|    SILVER|            2|               Japan|                  JPN|
|         Curling|        Women|beijing-2022|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            4|         Switzerland|                  SUI|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            5|              Canada|                  CAN|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            6|United States of ...|                  USA|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            7|People's Republic...|                  CHN|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            8|   Republic of Korea|                  KOR|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|            9|             Denmark|                  DEN|
|         Curling|        Women|beijing-2022|        GameTeam|      NULL|           10|                 ROC|                  ROC|
+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
only showing top 20 rows

In [65]:
data_result = data_result.fillna('0', subset=["medal_type"])

In [66]:
data_result.show()

+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
|discipline_title|  event_title|   game_slug|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|
+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|      GOLD|            1|               Italy|                  ITA|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    SILVER|            2|              Norway|                  NOR|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            4|       Great Britain|                  GBR|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            5|              Canada|                  CAN|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            6|      Czech Republic|                  CZE|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            7|         Switzerland|                  SUI|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            8|United States of ...|                  USA|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|            9|People's Republic...|                  CHN|
|         Curling|Mixed Doubles|beijing-2022|        GameTeam|         0|           10|           Australia|                  AUS|
|         Curling|        Women|beijing-2022|        GameTeam|      GOLD|            1|       Great Britain|                  GBR|
|         Curling|        Women|beijing-2022|        GameTeam|    SILVER|            2|               Japan|                  JPN|
|         Curling|        Women|beijing-2022|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            4|         Switzerland|                  SUI|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            5|              Canada|                  CAN|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            6|United States of ...|                  USA|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            7|People's Republic...|                  CHN|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            8|   Republic of Korea|                  KOR|
|         Curling|        Women|beijing-2022|        GameTeam|         0|            9|             Denmark|                  DEN|
|         Curling|        Women|beijing-2022|        GameTeam|         0|           10|                 ROC|                  ROC|
+----------------+-------------+------------+----------------+----------+-------------+--------------------+---------------------+
only showing top 20 rows

### Analyse et traitement du dataset data medal :

In [67]:
data_medal.show()

+----------------+------------+--------------------+------------+----------+----------------+-----------------+--------------------+--------------------+--------------------+------------+---------------------+
|discipline_title|   game_slug|         event_title|event_gender|medal_type|participant_type|participant_title|         athlete_url|   athlete_full_name|        country_name|country_code|country_3_letter_code|
+----------------+------------+--------------------+------------+----------+----------------+-----------------+--------------------+--------------------+--------------------+------------+---------------------+
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|      GOLD|        GameTeam|            Italy|https://olympics....|Stefania CONSTANTINI|               Italy|          IT|                  ITA|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|      GOLD|        GameTeam|            Italy|https://olympics....|        Amos MOSANER|               Italy|          IT|                  ITA|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    SILVER|        GameTeam|           Norway|https://olympics....|    Kristin SKASLIEN|              Norway|          NO|                  NOR|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    SILVER|        GameTeam|           Norway|https://olympics....|  Magnus NEDREGOTTEN|              Norway|          NO|                  NOR|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    BRONZE|        GameTeam|           Sweden|https://olympics....|       Almida DE VAL|              Sweden|          SE|                  SWE|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    BRONZE|        GameTeam|           Sweden|https://olympics....|      Oskar ERIKSSON|              Sweden|          SE|                  SWE|
|         Curling|beijing-2022|               Women|       Women|      GOLD|        GameTeam|    Great Britain|                NULL|                NULL|       Great Britain|          GB|                  GBR|
|         Curling|beijing-2022|               Women|       Women|    SILVER|        GameTeam|            Japan|                NULL|                NULL|               Japan|          JP|                  JPN|
|         Curling|beijing-2022|               Women|       Women|    BRONZE|        GameTeam|           Sweden|                NULL|                NULL|              Sweden|          SE|                  SWE|
|         Curling|beijing-2022|                 Men|         Men|      GOLD|        GameTeam|           Sweden|                NULL|                NULL|              Sweden|          SE|                  SWE|
|         Curling|beijing-2022|                 Men|         Men|    SILVER|        GameTeam|    Great Britain|                NULL|                NULL|       Great Britain|          GB|                  GBR|
|         Curling|beijing-2022|                 Men|         Men|    BRONZE|        GameTeam|           Canada|                NULL|                NULL|              Canada|          CA|                  CAN|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|    SILVER|         Athlete|             NULL|https://olympics....|    Mikael KINGSBURY|              Canada|          CA|                  CAN|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|      GOLD|         Athlete|             NULL|https://olympics....|     Walter WALLBERG|              Sweden|          SE|                  SWE|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|    BRONZE|         Athlete|             NULL|https://olympics....|     Ikuma HORISHIMA|               Japan|          JP|                  JPN|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|      GOLD|         Athlete|             NULL|https://olympics....|       Nico PORTEOUS|         New Zealand|          NZ|                  NZL|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|    SILVER|         Athlete|             NULL|https://olympics....|          David WISE|United States of ...|          US|                  USA|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|    BRONZE|         Athlete|             NULL|https://olympics....|       Alex FERREIRA|United States of ...|          US|                  USA|
|Freestyle Skiing|beijing-2022|Men's Freeski Big...|         Men|    BRONZE|         Athlete|             NULL|https://olympics....|      Henrik HARLAUT|              Sweden|          SE|                  SWE|
|Freestyle Skiing|beijing-2022|Men's Freeski Big...|         Men|      GOLD|         Athlete|             NULL|https://olympics....|           Birk RUUD|              Norway|          NO|                  NOR|
+----------------+------------+--------------------+------------+----------+----------------+-----------------+--------------------+--------------------+--------------------+------------+---------------------+
only showing top 20 rows

In [68]:
data_medal.printSchema()

root
 |-- discipline_title: string (nullable = true)
 |-- game_slug: string (nullable = true)
 |-- event_title: string (nullable = true)
 |-- event_gender: string (nullable = true)
 |-- medal_type: string (nullable = true)
 |-- participant_type: string (nullable = true)
 |-- participant_title: string (nullable = true)
 |-- athlete_url: string (nullable = true)
 |-- athlete_full_name: string (nullable = true)
 |-- country_name: string (nullable = true)
 |-- country_code: string (nullable = true)
 |-- country_3_letter_code: string (nullable = true)

In [69]:
data_medal.count()

21697

In [70]:
data_medal=data_medal.drop("participant_title")
data_medal=data_medal.drop("athlete_url")
data_medal=data_medal.drop("country_name")
data_medal=data_medal.drop("country_code")

In [71]:
data_medal.show()

+----------------+------------+--------------------+------------+----------+----------------+--------------------+---------------------+
|discipline_title|   game_slug|         event_title|event_gender|medal_type|participant_type|   athlete_full_name|country_3_letter_code|
+----------------+------------+--------------------+------------+----------+----------------+--------------------+---------------------+
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|      GOLD|        GameTeam|Stefania CONSTANTINI|                  ITA|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|      GOLD|        GameTeam|        Amos MOSANER|                  ITA|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    SILVER|        GameTeam|    Kristin SKASLIEN|                  NOR|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    SILVER|        GameTeam|  Magnus NEDREGOTTEN|                  NOR|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    BRONZE|        GameTeam|       Almida DE VAL|                  SWE|
|         Curling|beijing-2022|       Mixed Doubles|       Mixed|    BRONZE|        GameTeam|      Oskar ERIKSSON|                  SWE|
|         Curling|beijing-2022|               Women|       Women|      GOLD|        GameTeam|                NULL|                  GBR|
|         Curling|beijing-2022|               Women|       Women|    SILVER|        GameTeam|                NULL|                  JPN|
|         Curling|beijing-2022|               Women|       Women|    BRONZE|        GameTeam|                NULL|                  SWE|
|         Curling|beijing-2022|                 Men|         Men|      GOLD|        GameTeam|                NULL|                  SWE|
|         Curling|beijing-2022|                 Men|         Men|    SILVER|        GameTeam|                NULL|                  GBR|
|         Curling|beijing-2022|                 Men|         Men|    BRONZE|        GameTeam|                NULL|                  CAN|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|    SILVER|         Athlete|    Mikael KINGSBURY|                  CAN|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|      GOLD|         Athlete|     Walter WALLBERG|                  SWE|
|Freestyle Skiing|beijing-2022|        Men's Moguls|         Men|    BRONZE|         Athlete|     Ikuma HORISHIMA|                  JPN|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|      GOLD|         Athlete|       Nico PORTEOUS|                  NZL|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|    SILVER|         Athlete|          David WISE|                  USA|
|Freestyle Skiing|beijing-2022|Men's Freeski Hal...|         Men|    BRONZE|         Athlete|       Alex FERREIRA|                  USA|
|Freestyle Skiing|beijing-2022|Men's Freeski Big...|         Men|    BRONZE|         Athlete|      Henrik HARLAUT|                  SWE|
|Freestyle Skiing|beijing-2022|Men's Freeski Big...|         Men|      GOLD|         Athlete|           Birk RUUD|                  NOR|
+----------------+------------+--------------------+------------+----------+----------------+--------------------+---------------------+
only showing top 20 rows

In [72]:
data_medal.groupBy("country_3_letter_code").count().show(100)

+---------------------+-----+
|country_3_letter_code|count|
+---------------------+-----+
|                  POL|  345|
|                  BUR|    1|
|                  JAM|   86|
|                  BRA|  180|
|                  ARM|   18|
|                  MOZ|    2|
|                  CUB|  239|
|                  JOR|    3|
|                  FRA|  952|
|                  ALG|   17|
|                  BRN|    4|
|                  VIE|    4|
|                  BOT|    2|
|                  RSA|   95|
|                  ETH|   57|
|                  ITA|  805|
|                  UKR|  159|
|                  GHA|    5|
|                  OAR|   18|
|                  CMR|    6|
|                  SCG|    9|
|                  SEN|    1|
|                  AHO|    1|
|                  GUY|    1|
|                  TOG|    1|
|                  QAT|    9|
|                  GUA|    1|
|                  GBR| 1045|
|                  TCH|  178|
|                  FIJ|    3|
|                  TJK|    4|
|                  ERI|    1|
|                  UGA|   11|
|                  ZIM|    8|
|                  AZE|   50|
|                  AUS|  627|
|                  PUR|   10|
|                  MEX|   77|
|                  PAR|    1|
|                  AFG|    2|
|                  SRI|    2|
|                  SLO|   56|
|                  TGA|    1|
|                  GDR|  562|
|                  SUD|    1|
|                  BLR|  113|
|                  SVK|   47|
|                  NIG|    2|
|                  HUN|  559|
|                  TKM|    1|
|                  NZL|  173|
|                  MRI|    1|
|                  THA|   35|
|                  DJI|    1|
|                  NOR|  589|
|                  KOS|    3|
|                  IRQ|    1|
|                  VEN|   19|
|                  FIN|  490|
|                  POR|   33|
|                  DEN|  233|
|                  DOM|   12|
|                  UAR|    2|
|                  SUR|    2|
|                  BAH|   18|
|                  URU|   12|
|                  NED|  501|
|                  PER|    4|
|                  PAK|   10|
|                  EUN|  141|
|                  LUX|    5|
|                  TUR|  103|
|                  IOA|    5|
|                  MNE|    1|
|                  AUT|  371|
|                  BDI|    2|
|                  USA| 3094|
|                  MAR|   24|
|                  GEO|   40|
|                  PAN|    3|
|                  CIV|    4|
|                  KOR|  393|
|                  PRK|   58|
|                  LIE|   10|
|                  GER| 1167|
|                  ISR|   13|
|                  TUN|   15|
|                  NAM|    5|
|                  SMR|    4|
|                  LTU|   30|
|                  CYP|    1|
|                  YUG|   94|
|                  UAE|    2|
|                  CRC|    4|
|                  BOH|    4|
|                  CAN|  602|
|                  MAS|   19|
|                  SUI|  402|
|                  COL|   34|
|                  RUS|  599|
+---------------------+-----+
only showing top 100 rows

### Analyse et traitement du dataset data host :

In [73]:
data_host.show()

+-------------------+-------------------+-------------------+------------------+-------------------+-----------+---------+
|          game_slug|      game_end_date|    game_start_date|     game_location|          game_name|game_season|game_year|
+-------------------+-------------------+-------------------+------------------+-------------------+-----------+---------+
|       beijing-2022|2022-02-20 13:00:00|2022-02-04 16:00:00|             China|       Beijing 2022|     Winter|     2022|
|         tokyo-2020|2021-08-08 16:00:00|2021-07-23 13:00:00|             Japan|         Tokyo 2020|     Summer|     2020|
|   pyeongchang-2018|2018-02-25 09:00:00|2018-02-09 00:00:00| Republic of Korea|   PyeongChang 2018|     Winter|     2018|
|           rio-2016|2016-08-21 23:00:00|2016-08-05 14:00:00|            Brazil|           Rio 2016|     Summer|     2016|
|         sochi-2014|2014-02-23 17:00:00|2014-02-07 05:00:00|Russian Federation|         Sochi 2014|     Winter|     2014|
|        london-2012|2012-08-12 21:00:00|2012-07-27 09:00:00|     Great Britain|        London 2012|     Summer|     2012|
|     vancouver-2010|2010-02-28 05:00:00|2010-02-12 17:00:00|            Canada|     Vancouver 2010|     Winter|     2010|
|       beijing-2008|2008-08-24 14:00:00|2008-08-08 02:00:00|             China|       Beijing 2008|     Summer|     2008|
|         turin-2006|2006-02-26 20:00:00|2006-02-10 08:00:00|             Italy|         Turin 2006|     Winter|     2006|
|        athens-2004|2004-08-29 20:00:00|2004-08-13 08:00:00|            Greece|        Athens 2004|     Summer|     2004|
|salt-lake-city-2002|2002-02-24 09:00:00|2002-02-08 16:00:00|     United States|Salt Lake City 2002|     Winter|     2002|
|        sydney-2000|2000-10-01 11:00:00|2000-09-15 03:00:00|         Australia|        Sydney 2000|     Summer|     2000|
|        nagano-1998|1998-02-22 12:00:00|1998-02-07 00:00:00|             Japan|        Nagano 1998|     Winter|     1998|
|       atlanta-1996|1996-08-05 23:00:00|1996-07-19 14:00:00|     United States|       Atlanta 1996|     Summer|     1996|
|   lillehammer-1994|1994-02-27 20:00:00|1994-02-12 08:00:00|            Norway|   Lillehammer 1994|     Winter|     1994|
|     barcelona-1992|1992-08-09 20:00:00|1992-07-25 08:00:00|             Spain|     Barcelona 1992|     Summer|     1992|
|   albertville-1992|1992-02-23 20:00:00|1992-02-08 08:00:00|            France|   Albertville 1992|     Winter|     1992|
|         seoul-1988|1988-10-02 11:00:00|1988-09-17 00:00:00| Republic of Korea|         Seoul 1988|     Summer|     1988|
|       calgary-1988|1988-02-28 04:00:00|1988-02-13 16:00:00|            Canada|       Calgary 1988|     Winter|     1988|
|   los-angeles-1984|1984-08-12 21:00:00|1984-07-28 17:00:00|     United States|   Los Angeles 1984|     Summer|     1984|
+-------------------+-------------------+-------------------+------------------+-------------------+-----------+---------+
only showing top 20 rows

In [74]:
data_host.printSchema()

root
 |-- game_slug: string (nullable = true)
 |-- game_end_date: timestamp (nullable = true)
 |-- game_start_date: timestamp (nullable = true)
 |-- game_location: string (nullable = true)
 |-- game_name: string (nullable = true)
 |-- game_season: string (nullable = true)
 |-- game_year: integer (nullable = true)

In [75]:
data_host.count()

53

### enregistrement des 4 dataset nettoyer:

In [76]:
data_host.write.csv("Clean_Data/cleaned_host.csv", header=True, mode='overwrite')
data_medal.write.csv("Clean_Data/cleaned_medal.csv", header=True, mode='overwrite')
data_athletes.write.csv("Clean_Data/cleaned_ahletes.csv", header=True, mode='overwrite')
data_result.write.csv("Clean_Data/cleaned_result.csv", header=True, mode='overwrite')

In [77]:
final_data=data_result

In [78]:
final_data=final_data.join(data_host, on='game_slug')

In [79]:
final_data.show()

+------------+----------------+-------------+----------------+----------+-------------+--------------------+---------------------+-------------------+-------------------+-------------+------------+-----------+---------+
|   game_slug|discipline_title|  event_title|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|      game_end_date|    game_start_date|game_location|   game_name|game_season|game_year|
+------------+----------------+-------------+----------------+----------+-------------+--------------------+---------------------+-------------------+-------------------+-------------+------------+-----------+---------+
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|      GOLD|            1|               Italy|                  ITA|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|    SILVER|            2|              Norway|                  NOR|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            4|       Great Britain|                  GBR|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            5|              Canada|                  CAN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            6|      Czech Republic|                  CZE|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            7|         Switzerland|                  SUI|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            8|United States of ...|                  USA|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|            9|People's Republic...|                  CHN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|Mixed Doubles|        GameTeam|         0|           10|           Australia|                  AUS|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|      GOLD|            1|       Great Britain|                  GBR|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|    SILVER|            2|               Japan|                  JPN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|    BRONZE|            3|              Sweden|                  SWE|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            4|         Switzerland|                  SUI|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            5|              Canada|                  CAN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            6|United States of ...|                  USA|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            7|People's Republic...|                  CHN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            8|   Republic of Korea|                  KOR|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|            9|             Denmark|                  DEN|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
|beijing-2022|         Curling|        Women|        GameTeam|         0|           10|                 ROC|                  ROC|2022-02-20 13:00:00|2022-02-04 16:00:00|        China|Beijing 2022|     Winter|     2022|
+------------+----------------+-------------+----------------+----------+-------------+--------------------+---------------------+-------------------+-------------------+-------------+------------+-----------+---------+
only showing top 20 rows

In [80]:
data_host.printSchema()

root
 |-- game_slug: string (nullable = true)
 |-- game_end_date: timestamp (nullable = true)
 |-- game_start_date: timestamp (nullable = true)
 |-- game_location: string (nullable = true)
 |-- game_name: string (nullable = true)
 |-- game_season: string (nullable = true)
 |-- game_year: integer (nullable = true)

In [81]:
final_data=final_data.drop("game_end_date")
final_data=final_data.drop("game_start_date")
final_data=final_data.drop("game_name")
final_data=final_data.drop("game_location")

In [82]:
final_data.printSchema()

root
 |-- game_slug: string (nullable = true)
 |-- discipline_title: string (nullable = true)
 |-- event_title: string (nullable = true)
 |-- participant_type: string (nullable = true)
 |-- medal_type: string (nullable = false)
 |-- rank_position: string (nullable = true)
 |-- country_name: string (nullable = true)
 |-- country_3_letter_code: string (nullable = true)
 |-- game_season: string (nullable = true)
 |-- game_year: integer (nullable = true)

In [83]:
final_data = final_data.filter(final_data['game_season'] == 'Summer')

In [84]:
final_data.count()

117159

In [85]:
final_data.show()

+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+
| game_slug|discipline_title|         event_title|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|game_season|game_year|
+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|      GOLD|            1|               Spain|                  ESP|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|    SILVER|            2|          San Marino|                  SMR|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|    BRONZE|            3|United States of ...|                  USA|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            4|            Slovakia|                  SVK|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            5|               Japan|                  JPN|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            6|           Australia|                  AUS|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            7|           Australia|                  AUS|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            8|            Slovakia|                  SVK|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            9|People's Republic...|                  CHN|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           10|       Great Britain|                  GBR|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           11|                 ROC|                  ROC|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           12|               Italy|                  ITA|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           13|United States of ...|                  USA|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           14|                 ROC|                  ROC|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           15|              Mexico|                  MEX|     Summer|     2020|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           16|               Egypt|                  EGY|     Summer|     2020|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|           19|People's Republic...|                  CHN|     Summer|     2020|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|            5|United States of ...|                  USA|     Summer|     2020|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|           17|             Belarus|                  BLR|     Summer|     2020|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|    BRONZE|            3|                 ROC|                  ROC|     Summer|     2020|
+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+
only showing top 20 rows

In [86]:
final_data = final_data.withColumn(
    'm_total', when(col('medal_type') == 'None', 0).otherwise(1)
).withColumn(
    'm_gold', when(col('medal_type') == 'GOLD', 1).otherwise(0)
).withColumn(
    'm_silver', when(col('medal_type') == 'SILVER', 1).otherwise(0)
).withColumn(
    'm_bronze', when(col('medal_type') == 'BRONZE', 1).otherwise(0)
)

## regroupement des donnees dans un seul dataset pour l'apprentissage

In [87]:
final_data.show()

+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
| game_slug|discipline_title|         event_title|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|game_season|game_year|m_total|m_gold|m_silver|m_bronze|
+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|      GOLD|            1|               Spain|                  ESP|     Summer|     2020|      1|     1|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|    SILVER|            2|          San Marino|                  SMR|     Summer|     2020|      1|     0|       1|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|    BRONZE|            3|United States of ...|                  USA|     Summer|     2020|      1|     0|       0|       1|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            4|            Slovakia|                  SVK|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            5|               Japan|                  JPN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            6|           Australia|                  AUS|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            7|           Australia|                  AUS|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            8|            Slovakia|                  SVK|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|            9|People's Republic...|                  CHN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           10|       Great Britain|                  GBR|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           11|                 ROC|                  ROC|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           12|               Italy|                  ITA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           13|United States of ...|                  USA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           14|                 ROC|                  ROC|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           15|              Mexico|                  MEX|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|     Trap Mixed Team|        GameTeam|         0|           16|               Egypt|                  EGY|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|           19|People's Republic...|                  CHN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|            5|United States of ...|                  USA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|         0|           17|             Belarus|                  BLR|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Shooting|50m Rifle 3 Posit...|         Athlete|    BRONZE|            3|                 ROC|                  ROC|     Summer|     2020|      1|     0|       0|       1|
+----------+----------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
only showing top 20 rows

In [88]:
final_data_no_duplicates = final_data.dropDuplicates()

In [89]:
final_data_no_duplicates.show()

+----------+--------------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
| game_slug|    discipline_title|         event_title|participant_type|medal_type|rank_position|        country_name|country_3_letter_code|game_season|game_year|m_total|m_gold|m_silver|m_bronze|
+----------+--------------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
|tokyo-2020|              Diving|Men's Synchronise...|        GameTeam|    BRONZE|            3|             Germany|                  GER|     Summer|     2020|      1|     0|       0|       1|
|tokyo-2020|              Diving|  Men's 10m Platform|         Athlete|         0|            9|United States of ...|                  USA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Canoe Sprint|Men's Kayak Doubl...|        GameTeam|         0|            4|             Hungary|                  HUN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Canoe Sprint|Men's Canoe Singl...|         Athlete|         0|            8|People's Republic...|                  CHN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Cycling Road|   Women's Road Race|         Athlete|         0|          DNF|             Belgium|                  BEL|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Cycling Road|Men's Individual ...|         Athlete|         0|            5|               Italy|                  ITA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|        Cycling Road|     Men's Road Race|         Athlete|         0|           29|             Germany|                  GER|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|            Football|                 Men|        GameTeam|         0|           13|              France|                  FRA|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|              Boxing|Men's Super Heavy...|         Athlete|    SILVER|            2|United States of ...|                  USA|     Summer|     2020|      1|     0|       1|       0|
|tokyo-2020|              Boxing|Women's Light (57...|         Athlete|         0|            5|          Uzbekistan|                  UZB|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|              Boxing| Men's Fly (48-52kg)|         Athlete|         0|           17|            Botswana|                  BOT|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|   Marathon Swimming|          Men's 10km|         Athlete|         0|           23|            Portugal|                  POR|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|Trampoline Gymnas...|                 Men|         Athlete|      GOLD|            1|             Belarus|                  BLR|     Summer|     2020|      1|     1|       0|       0|
|tokyo-2020|           Taekwondo|           Men -80kg|         Athlete|         0|           11|               Spain|                  ESP|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|       Cycling Track|        Men's Sprint|         Athlete|         0|           13|            Suriname|                  SUR|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|             Fencing|Women's ÃpÃ©e In...|         Athlete|         0|            9|People's Republic...|                  CHN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|             Fencing|   Women's Foil Team|        GameTeam|         0|            6|               Japan|                  JPN|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|           Badminton|       Men's Singles|         Athlete|         0|            5|      Chinese Taipei|                  TPE|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020|              Tennis|       Men's Singles|         Athlete|         0|           17|      Czech Republic|                  CZE|     Summer|     2020|      1|     0|       0|       0|
|tokyo-2020| Artistic Gymnastics|    Men's All-Around|         Athlete|         0|           11|             Ukraine|                  UKR|     Summer|     2020|      1|     0|       0|       0|
+----------+--------------------+--------------------+----------------+----------+-------------+--------------------+---------------------+-----------+---------+-------+------+--------+--------+
only showing top 20 rows

In [90]:
final_data.count()

117159

In [91]:
final_data_no_duplicates.count()

112529

In [92]:
final_data_no_duplicates=final_data_no_duplicates.drop("country_code")

In [93]:
Final_data_df=final_data_no_duplicates.toPandas()

In [94]:
Final_data_df.to_csv("Dataset.csv",index=False)